# This is a basic workflow to deploy the daily grower website every morning at 3am Central
name: weekday-main-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  workflow_dispatch:
  schedule:
  - cron: "0 9 * * 1-5"

# Deploy using a netlify build hook
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: fjogeleit/http-request-action@master
      with:
        url: 'https://api.netlify.com/build_hooks/5fb0bcf3f71623a5bcd95256?trigger_branch=main&trigger_title=github+weekday+deploy'
        method: 'POST'
        data: '{"BUILD_TYPE": "weekday", "DEPLOY_TYPE": "production"}'
